#:schema https://github.com/jdx/mise/blob/main/schema/mise.json
# ONLY USE THIS FOR MACHINE-AGNOSTIC CONFIG.

[env]
EDITOR = { value = "{{ exec(command='which nvim') }}", tools = true }
ZSH = "{{ env.HOME }}/.oh-my-zsh"

[settings]
ignored_config_paths = ["{{ exec(command='chezmoi source-path') }}"]

[tools]
chezmoi = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
zoxide = "latest"
