#:schema https://github.com/jdx/mise/blob/main/schema/mise.json
# ONLY USE THIS FOR MACHINE-AGNOSTIC CONFIG.

[env]
EDITOR = { value = "{{ exec(command='which nvim') }}", tools = true }
LG_CONFIG_FILE = "{{ get_env(name='HOME') }}/.config/lazygit/config.yml"

[settings]
ignored_config_paths = ["{{ exec(command='chezmoi source-path') }}"]

[tools]
chezmoi = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
ninja = 'latest'
ripgrep = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
zoxide = "latest"
