[[work.filters]]
After = "2020-01-01"

[[work.filters]]
Exclude = "Sandbox at Northeastern University"

[[projects.filters]]
Include = "Compiler for Python-like Language"

# [[projects.filters]]
# Include = "ply"
#
# [[projects.filters]]
# Include = "reze"
