require 'plugins.colorscheme'
require 'plugins.snacks'
require 'plugins.lsp'
require 'plugins.completion'
require 'plugins.formatting'
require 'plugins.lint'
require 'plugins.navigation'
require 'plugins.treesitter'
-- require 'plugins.debug'
require 'plugins.ui'
