alias ca="chezmoi apply"
alias ccd="chezmoi cd"
alias lg="lazygit"
alias ls="eza"
alias n="nvim ."

# git
alias g="git"
alias gP="git push"
alias ga="git add"
alias gcm="git commit -m"
alias gco="git checkout"
alias gf="git fetch origin"
alias gp="git pull"
alias gst="git status"
